[package]
name = "convolutions-rs-benchmarks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convolutions-rs = "0.2.1"
ndarray-rand = "0.14.0"
ndarray = "0.15.3"
